version: "2"
services:
  lddtool-web-service:
    container_name: lddtool-web-service
    restart: always
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    env_file:
      - ./services.env